version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: influencer_db
    environment:
      POSTGRES_USER: influencer_user
      POSTGRES_PASSWORD: influencer_pass
      POSTGRES_DB: influencer_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U influencer_user -d influencer_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: influencer_backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://influencer_user:influencer_pass@postgres:5432/influencer_platform
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      NODE_ENV: development
      PORT: 3001
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: influencer_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_data:

