[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmd = "cd backend && NPM_CONFIG_PRODUCTION=false npm ci"

[phases.build]
cmd = "cd backend && npm run build && ls -la dist/ || true"

[start]
cmd = "cd backend && node dist/main.js"
