[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend Service
[[services]]
name = "backend"
root = "backend"
buildCommand = "npm ci"
startCommand = "npm run build && npm run start:prod"
healthcheckPath = "/api/health"
port = 3001

  [[services.envs]]
  NODE_ENV = "production"
  
# Frontend Service
[[services]]
name = "frontend"  
root = "frontend"
buildCommand = "npm ci && npm run build"
startCommand = "npm start"
healthcheckPath = "/"
port = 3000

  [[services.envs]]
  NODE_ENV = "production"
