[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --production=false && npm run build"

[deploy]
startCommand = "cd backend && node dist/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
